// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjpzdaqrtxkzdemclrvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqcHpkYXFydHhremRlbWNscnZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNDYzODMsImV4cCI6MjA3NTYyMjM4M30.3DwIR41-e82Dz2u-43xvSxIbl6NTxTxJlhtb4ImqNcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});